# Generated by Django 5.0.4 on 2024-04-24 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Transaction',
        ),
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.TextField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE'),
        ),
    ]
