# Generated by Django 5.0.4 on 2024-05-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_created_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_monthly_recurrring',
            new_name='is_monthly_recurring',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='is_monthly_recurrring',
            new_name='is_monthly_recurring',
        ),
    ]
