# Generated by Django 5.0.4 on 2024-04-25 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_expense_transaction_category_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="category",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="income",
            name="labels",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="income",
            name="notes",
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("category", models.TextField()),
                ("notes", models.TextField()),
                ("labels", models.TextField()),
                ("is_monthly_recurrring", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
